<a href="https://colab.research.google.com/github/ranu-commits/Data-Science-/blob/main/Numpy_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Array Creation**
1. How do you create a NumPy array from a Python list [1, 2, 3, 4]?
2. Create a NumPy array of shape (2, 3) filled with all zeros.
3. Create a NumPy array of shape (4, 2) filled with all ones.
4. How can you create a NumPy array with values ranging from 10 to 20, with a step
size of 2?
5. Create a 1D array of 10 equally spaced values between 1 and 5.

In [2]:
import numpy as np

arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [6]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# **2. Array Indexing and Slicing**
1. Given the array arr = np.array([1, 2, 3, 4, 5]), access the third element.
2. Slice the first three elements from the array arr = np.array([10, 20, 30, 40, 50]).
3. Given the 2D array arr = np.array([[1, 2], [3, 4], [5, 6]]), access the element in the
second row and first column.
4. Extract the second column from the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8,
9]]).
5. Reverse the array arr = np.array([1, 2, 3, 4, 5]) using slicing.

In [7]:
arr[2]

3

In [8]:
arr[ :3]

array([1, 2, 3])

In [9]:
arr2=np.array([[1,2],[3,4],[5,6]])
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr3[ :,1]

array([2, 5, 8])

In [12]:
#Reverse
arr[::-1]

array([4, 3, 2, 1])

# **3. Array Operations**
1. Given two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), add them together.
2. Subtract array b = np.array([4, 5, 6]) from array a = np.array([1, 2, 3]).
3. Multiply the array a = np.array([1, 2, 3]) by a scalar value of 5.
4. Divide the array a = np.array([10, 20, 30]) by a scalar value of 2.
5. Perform element-wise square of the array a = np.array([1, 2, 3, 4]).

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b
a-b
a*5
b/2
a**2

array([1, 4, 9])

# **4. Array Reshaping**
1. Given an array arr = np.array([1, 2, 3, 4, 5, 6]), reshape it into a (2, 3) array.
2. Reshape the array arr = np.array([1, 2, 3, 4]) into a (4, 1) array.

3. Reshape the array arr = np.array([1, 2, 3, 4, 5, 6]) into a (3, 2) array.
4. Given a (4, 3) array, flatten it into a 1D array.
5. Convert a 1D array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) into a 2D array with shape (2,
4).

In [14]:
arr1=np.array([1,2,3,4,5,6])
arr1.reshape(2,3)
arr1.reshape(6,1)
arr1.reshape(3,2)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,0]])
arr2
arr2.reshape(1,12)
arr3=np.array([1,2,3,4,5,6,7,8])
arr3.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# **5. Array Statistics and Aggregation**
1. Find the sum of all elements in the array arr = np.array([1, 2, 3, 4, 5]).
2. Find the maximum value in the array arr = np.array([10, 20, 30, 40, 50]).
3. Calculate the mean of the array arr = np.array([1, 2, 3, 4, 5]).
4. Find the standard deviation of the array arr = np.array([1, 4, 7, 10]).
5. Given a 2D array arr = np.array([[1, 2, 3], [4, 5, 6]]), calculate the sum of each
column.

In [15]:
arr1=np.array([1,2,3,4,5,6])
arr1.sum()
arr1.max()
arr1.mean()
arr1.std()
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.sum(axis=0) # column wise sum

array([12, 15, 18])

# **6. Array Broadcasting**
1. Add a scalar value of 5 to the array arr = np.array([1, 2, 3]).
2. Multiply each element of the array arr = np.array([1, 2, 3]) by a scalar value of 2.
3. Add the arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]).
4. Multiply a 1D array a = np.array([1, 2, 3]) with a 2D array b = np.array([[1], [2], [3]]).
5. Subtract a scalar value of 10 from each element of the array arr = np.array([15, 20,
25]).

In [16]:
arr=np.array([1,2,3])
arr +5
arr *2
a,b=np.array([1,2,3]),np.array([4,5,6])
a+b
a*b
np.array([15,20,30]) -10

array([ 5, 10, 20])

# **7. Random Number Generation**
1. Generate a random float between 0 and 1.
2. Create an array of 5 random integers between 1 and 10 (inclusive).
3. Create a 2x3 array of random integers between 1 and 100.
4. Create a random 3x3 matrix from a normal distribution with mean 0 and standard
deviation 1.

5. Set a seed of 42 and generate a 4x4 array of random numbers between 0 and 1.

In [17]:
np.random.rand(3,2)

array([[0.80757195, 0.16347657],
       [0.52590182, 0.79706047],
       [0.20258111, 0.94086352]])

In [18]:
np.random.randint(1,10,5)

array([8, 6, 4, 4, 3])

In [19]:
np.random.randint(1,100,(2,3))

array([[23, 38, 62],
       [97, 79, 97]])

In [20]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.random.rand(4,4)


array([[0.99599747, 0.75984336, 0.41318278, 0.69739156],
       [0.80682945, 0.30062629, 0.89611428, 0.06747098],
       [0.70039253, 0.05540496, 0.10019088, 0.39742915],
       [0.49330677, 0.59701593, 0.52818962, 0.00941713]])

In [22]:
seed=np.random.seed(42)
print(seed)

None


# **8. Array Conditions and Filtering**
1. Given the array arr = np.array([1, 2, 3, 4, 5]), filter out elements that are greater than 3.
2. Check if all elements in the array arr = np.array([True, False, True]) are True.
3. Find the indices of elements in the array arr = np.array([1, 2, 3, 4, 5]) that are greater
than 2.
4. Create a boolean array where the elements of arr = np.array([10, 20, 30, 40, 50]) are
less than 30.
5. Use np.where() to find elements greater than 15 in the array arr = np.array([10, 20,
30, 40, 50]) and replace them with 100.

In [23]:
[np.array([1,2,3,4,5])>3]

[array([False, False, False,  True,  True])]

In [24]:
arr1=np.array([1,2,3,4,5])
arr[arr1 >3]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5

In [ ]:
arr=np.array([True,False,True])
arr[arr==True]

In [ ]:
np.where(arr1>2)

In [ ]:
[np.array([10,20,30,40,50])<30]

In [ ]:
arr1=np.array([10,20,30,40,50])
np.where(arr1>15,100,arr1)

# **9. Linear Algebra Operations**
1. Find the dot product of two vectors a = np.array([1, 2]) and b = np.array([3, 4]).
2. Given two 2D arrays A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]),
calculate the matrix multiplication of A and B.
3. Find the determinant of the matrix A = np.array([[1, 2], [3, 4]]).
4. Compute the inverse of the matrix A = np.array([[1, 2], [3, 4]]).
5. Find the eigenvalues of the matrix A = np.array([[4, 2], [1, 3]]).

In [25]:
a=np.array([1,2])
b=np.array([3,4])
np.dot(a,b)

11

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.matmul(A,B) # Matrix Multiplication

In [ ]:
determinant=np.linalg.det(A)
determinant

In [ ]:
inverse=np.linalg.inv(A)
inverse

In [ ]:
eignavalue=np.linalg.eig(A)
eignavalue

In [ ]:
print(np.random.randint(1,10))
print(np.random.seed(42))
print(np.random.randint(1,10))
print(np.random.seed(2))
print(np.random.randint(1,10))
print(np.random.seed(42))
print(np.random.randint(1,10))

# **10. Set Operations with Arrays**
1. Given two arrays a = np.array([1, 2, 3]) and b = np.array([3, 4, 5]), find their union.
2. Find the intersection of arrays a = np.array([1, 2, 3]) and b = np.array([3, 4, 5]).
3. Given arrays a = np.array([1, 2, 3]) and b = np.array([2, 3, 4]), find the difference
between them (a - b).
4. Find the symmetric difference between a = np.array([1, 2, 3]) and b = np.array([3, 4,
5]).

5. Check if a = np.array([1, 2, 3]) is a subset of b = np.array([1, 2, 3, 4]).

In [27]:
a=np.array([1,2,3])
b=np.array([3,4,5])
np.union1d(a,b)

array([1, 2, 3, 4, 5])

In [28]:
np.intersect1d(a,b)

array([3])

In [29]:
np.setdiff1d(a,b)

array([1, 2])

In [30]:
np.setxor1d(a,b)

array([1, 2, 4, 5])

In [32]:
np.all(np.in1d(a,b))

False